### ISSUE TITLE
I can't buy anything except for bags

### ISSUE THREAD

**Issue by jrjaro18** [gamechanger2580/Scatch#1]
Very limited scope :( 
even all bags are not available, abibas bag isn't available ಥ_ಥ

![image](https://github.com/user-attachments/assets/67aa0195-c37a-453d-b56b-788789f69e6e)

**Comment by gamechanger2580** [comment]
Sorry for the inconvenience sir , will make them available on 29th Feb 2025. 😂, till then request abibas , adibas website for the same.
